### ISSUE TITLE
How to use React Native sdk for Authorization flow as webview

### ISSUE THREAD

**Issue by Shenith** [PayHereLK/payhere-mobilesdk-reactnative#15]
@payhere/payhere-mobilesdk-reactnative package only contain these payment methods only.

1. One-time Payment Request
2. Recurring Payment Request
3. Preapproval Request

But I need to hold the payment using Authorize API. That feature already have in webview. How can I do this from React Native sdk?

**Comment by PayHereDevs** [comment]
Hi @Shenith, apologies for the late reply.

Support for the Hold & Capture (Authorize & Capture) payment method is currently being added to the PayHere Mobile SDKs. Once it is added, we will update all SDKs (including React Native SDK) to support this feature.

**Comment by PayHereDevs** [comment]
Hi @Shenith, hope you are doing well.

It took some time but support for the Authorization flow has finally arrived in the PayHere React Native SDK. If you would like, you can check it out by updating to the latest version as follows.

```json
{
  "dependencies": {
    "@payhere/payhere-mobilesdk-reactnative": "3.0.0"
  }
}
```

__Here's a full list of things we changed:__

1. Added support for PayHere Hold-on-Card (Authorization).
2. Added support for passing line item details.
3. Fixed currency issues on iOS devices.
4. Removed requirement for hard-coding the merchant secret.
5. Added support for accepting both String and numerical amounts.

**Comment by Shenith** [comment]
Thank you @PayHereDevs
