### ISSUE TITLE
Undefined symbol: Swift._ArrayBuffer._copyContents(initializing: Swift.UnsafeMutableBufferPointer<A>) -> (Swift.IndexingIterator<Swift._ArrayBuffer<A>>, Swift.Int)

### ISSUE THREAD

**Issue by Damithijse** [PayHereLK/payhere-mobilesdk-reactnative#16]
When trying to build the React Native (Version 0.62.0) Project for iOS, the following error is shown.

**Comment by PayHereDevs** [comment]
Please refer to this issue. 

- https://github.com/PayHereLK/payhere-mobilesdk-reactnative/issues/13

If the mentioned fixes does not address your issue, please let us know. We will be glad to be of further support.

**Comment by Damithijse** [comment]
Thank you!  it's work for me 🎊 🎉
