### ISSUE TITLE
onDismissedHandler won't work on android

### ISSUE THREAD

**Issue by damithg-dev** [PayHereLK/payhere-mobilesdk-reactnative#3]
The startPayment call back of onDismissedHandler won't get fired on the android devices. In ios, it works as expected. herewith I attached the library version and device information  
Device Information : 
SM-M215F/DS
android 10

libraries version:  
`
    "@payhere/payhere-mobilesdk-reactnative": "1.0.5",
    "react": "16.13.1",
    "react-native": "0.63.4"
`
code sample snippet: https://snack.expo.io/yN1OlxOC0

**Comment by PayHereDevs** [comment]
Hello @damithg-dev!

Thanks for bringing this to our attention. We are working on getting this resolved. An update will be released soon with this fix.

**Comment by PayHereDevs** [comment]
Hi @damithg-dev,

We have added the required fixes to both iOS and Android code. Please use the following version and let us know if you encounter further issues. 

```json
{
  "dependencies": {
    "@payhere/payhere-mobilesdk-reactnative": "1.0.6"
  }
}
```

Sorry about the delay!

**Comment by damithg-dev** [comment]
Work like a charm. Thank you.

**Comment by PayHereDevs** [comment]
Hi Damith,

Thank you very much for your feedback!

We would be very grateful to you if you can put us a rating here if you're
happy with our solutions.

*Rate us: https://g.page/payhere/review?gm
<https://g.page/payhere/review?gm>*

Thank you!

--
*PayHere Support*

<https://www.payhere.lk/>
Need immediate support?
Message us via Live Messenger Support <http://m.me/PayHereLK>

Need to talk to us?
Call us Monday to Friday 9am to 6pm
Hotline 011 300 9975

PayHere (Private) Limited
No.46, Galle Road, Kalutara, Sri Lanka
Registration No: PV-113208
