### ISSUE TITLE
TypeError: null is not an object (evaluating '_reactNative.NativeModules.PayhereOfficial.startPayment')

### ISSUE THREAD

**Issue by RavinduJayasekara** [PayHereLK/payhere-mobilesdk-reactnative#4]
TypeError: null is not an object (evaluating '_reactNative.NativeModules.PayhereOfficial.startPayment')
- node_modules\react-native\Libraries\LogBox\LogBox.js:148:8 in registerError
- node_modules\react-native\Libraries\LogBox\LogBox.js:59:8 in errorImpl
- node_modules\react-native\Libraries\LogBox\LogBox.js:33:4 in console.error
- node_modules\expo\build\environment\react-native-logs.fx.js:27:4 in error
- node_modules\react-native\Libraries\Core\ExceptionsManager.js:104:6 in reportException
- node_modules\react-native\Libraries\Core\ExceptionsManager.js:171:19 in handleException
- node_modules\react-native\Libraries\Core\setUpErrorHandling.js:24:6 in handleError
- node_modules\expo-error-recovery\build\ErrorRecovery.fx.js:9:32 in ErrorUtils.setGlobalHandler$argument_0
- node_modules\regenerator-runtime\runtime.js:63:36 in tryCatch
- node_modules\regenerator-runtime\runtime.js:293:29 in invoke
- node_modules\regenerator-runtime\runtime.js:63:36 in tryCatch
- node_modules\regenerator-runtime\runtime.js:154:27 in invoke
- node_modules\regenerator-runtime\runtime.js:164:18 in PromiseImpl.resolve.then$argument_0
- node_modules\react-native\node_modules\promise\setimmediate\core.js:37:13 in tryCallOne
- node_modules\react-native\node_modules\promise\setimmediate\core.js:123:24 in setImmediate$argument_0
- node_modules\react-native\Libraries\Core\Timers\JSTimers.js:130:14 in _callTimer
- node_modules\react-native\Libraries\Core\Timers\JSTimers.js:181:14 in _callImmediatesPass
- node_modules\react-native\Libraries\Core\Timers\JSTimers.js:441:30 in callImmediates
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:387:6 in __callImmediates
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:135:6 in __guard$argument_0
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:364:10 in __guard
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:134:4 in flushedQueue
* [native code]:null in flushedQueue
* [native code]:null in invokeCallbackAndReturnFlushedQueue

import { StatusBar } from "expo-status-bar";
import React from "react";
import { StyleSheet, Text, View, Button } from "react-native";
import PayHere from "@payhere/payhere-mobilesdk-reactnative";

export default function App() {

  const fetchUrl = async () => {

    const paymentObject = {
      sandbox: true, // true if using Sandbox Merchant ID
      merchant_id: "", // Replace your Merchant ID
      merchant_secret: "", // See step 4e
      notify_url: "https://sandbox.payhere.lk/pay/checkout",
      order_id: "ItemNo12345",
      items: "Hello from React Native!",
      amount: "50.00",
      currency: "LKR",
      first_name: "Saman",
      last_name: "Perera",
      email: "samanp@gmail.com",
      phone: "0771234567",
      address: "No.1, Galle Road",
      city: "Colombo",
      country: "Sri Lanka",
      delivery_address: "No. 46, Galle road, Kalutara South",
      delivery_city: "Kalutara",
      delivery_country: "Sri Lanka",
      custom_1: "",
      custom_2: "",
    };

    try {
      PayHere.startPayment(
        paymentObject,
        (paymentId) => {
          console.log("Payment Completed", paymentId);
        },
        (errorData) => {
          Alert.alert("PayHere Error", errorData);
        },
        () => {
          console.log("Payment Dismissed");
        }
      );
    } catch (e) {
      console.log(e);
    }
  };

  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
      <Button title="Get it" onPress={fetchUrl} />
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
});

Please let me know what I am doing wrong ????

**Comment by PayHereDevs** [comment]
Hi Ravinud!

Apologies for the delayed response. `_reactNative.NativeModules.PayhereOfficial` evalutes to `null` when you have missed the step to perform the `react-native link` step.

Please try perform the command on your React Native project root and try rebuilding again. We will be glad to be of further support.

     react-native link @payhere/payhere-mobilesdk-reactnative
